# Kmeans
n_clusters = 140

# Word2Vec
min_count = 10 # mínimo de ocorrências para a palavra participar
window = 7 # janela de vetorização 
n_dim = 200 # dimensões do espaço vetorial

# Limites de palavras para um comentário tratado ser classificado
lower_limit = 3
upper_limit = 15


# Substituições extras (regex) para evitar clusters desnecessários (depois da lematização e do Unidecode). Adicionar sinônimos e typos.
dictionary = {' n ': ' nao ',
    'otima': 'bom',
    'otimo': 'bom',
    'excelente': 'bom',
    ' q ': ' que ', 
    ' pq ': ' porque ',
    ' p ': ' para ',
    'por que': 'porque',
    'pf ': 'por favor ',
    'pfv ': 'por favor ',
    'pfvr': 'por favor ',
    'poblem': 'problem',
    'hj': 'hoje',
    'oque': 'o que',
    'extorno': 'estorno',
    ' nd ': ' nada ',
    'ctt': 'contato',
    'efetivar': 'fazer',
    'aki': 'aqui',
    'agr ': 'agora ',
    'aguard': 'esper',
    'relatar': 'comentario',
    'voucher': 'vale',
    'efetuar': 'fazer',
    'whats ': 'whatsapp ',
    'ngm': 'ninguem',
    'tbm': 'tambem',
    'mto': 'muito',
    'vcs': 'voces',
    ' pro ': ' para o ',
    ' pra ': ' para a ',
    'mensagem pronto': 'mensagem automatica',
    ' mail': ' email',
    'markt': 'market',
    'plase': 'place',
    'site': 'loja',
    'loja': 'loja',
    'dafit': 'loja',
    ' app': ' loja',
    'empresa': 'loja',
    'aplicativo': 'loja',
    'informar que': 'dizer que',
    'https www reclameaqui br': 'reclame aqui',
    'mercadoria': 'pedido',
    'saber do': 'saber sobre',
    'empresa ': 'loja ',
    ' ver comentarios': ' ler comentarios',
    'produto': 'pedido',
    'item': 'pedido',
    ' comprar ': ' pedido ',
    'mudar': 'trocar',
    'receber': 'chegar',
    'entregar': 'chegar',
    'ate hoje': 'ate agora',
    'mandar': 'enviar',
    'obg': 'obrigado',
    'reembolsar': 'dinheiro',
    'ressarcimento': 'dinheiro',
    'ruim': 'mau',
    'mal': 'mau',
    'nunca ter': 'nao ter',
    'estornar': 'dinheiro',
    'msg': 'mensagem',
    'status': 'situacao',
    'ser entregar': 'chegar',
    'pior': 'mau',
    'enviar': 'mandar',
    'pos-vender': 'atendimento',
    'pos vender': 'atendimento',
    'resposta': 'retorno',
    'responder': 'retorno',
    ' to ': ' estou ',
    ' dia ': ' tempo ',
    ' mes ': ' tempo ',
    ' ano ': ' tempo ',
    'horrivel': 'mau',
    'entregar': 'recebido',
    'chegar': 'recebido',
    'adorar': 'amo',
    'cliente': 'consumidor',
    'extraviad': 'perdid'
}

remove_from_stopword_list = ['como', 'nem', 'não', 'mais', 'que', 'está', 'foi', 'será', 'quando', 'tive', 'até', 'sem'] # são stopwords, mas contribuem para o sentido do texto, portanto não são excluídas

add_to_stopword_list = ['pra', 'para']

useless_terms = ['fazer pedido', 'obrigar', 'numero pedido', 'pedido numero', 'bom dia', 'bom tarde', 'bom noite', 'tudo bem', 
    '(^|[^A-Za-zÀ-ÿ])(ola)[^A-Za-zÀ-ÿ]', # preceded by start of line or something that is not a letter
    '(^|[^A-Za-zÀ-ÿ])(ano)[^A-Za-zÀ-ÿ]', 
    '(^|[^A-Za-zÀ-ÿ])(amar)[^A-Za-zÀ-ÿ]',
    'assim', 'nessa', 'nesse', 'horar', 'ok', 'okay', 'loja'
] # remoção por regex, lematizados

blacklist = ['numero pedido', 'pedido numero'] # frases contendo esses termos são ignoradas (executada após unidecode)

ignorar = ['vale', 'pedido', 'reclame', 'nota', 'desconto', 'adidas', 'peça', 'peças']# ignorar na lematização


# Criação manual dos "clusters", que são compostos pelos resultados do K-means
'''
Não importa a ordem que os termos stemizados são colocados. O algoritmo dá prioridade aos termos mais frequentes dos subclusters criados pelo K-means.
'''

clusters = {'Amei comprar': ['am compr', 'sup rap', 'sup recomend', 'ador compr', 'gost compr'],
    'Cluster não identificado': ['que compr', 'compr loj', 'entreg temp', 'numer telefon', 'loj loj', 'que nao', 'ped que', 'ped ped', 'dinh dess'
                               'mand mens', 'entr contat', 'dess loj', 'cheg hoj',  'prec bom', 'mau qual', 'bom qual', 'melhor loj', # dúbio (ex: boa qualidade, péssima qualidade)
                               'problem loj', 'mais temp', 'present temp', 'dinh dess', 'vou compr', 'nao numer',
                               'compr tenil', 'vou ped', 'ped tenil', 'receb temp', 'compr temp', 'temp dia', 'mand ped'],
    'Endereço incorreto': ['enderec entreg', 'enderec err', 'alter enderec', 'coloc enderec', 'enderec antig'],
    'Estou tendo uma experiência ruim': ['mau experienc', 'mau serv'],
    'Estou tendo um problema': ['pass problem', 'sempr problem', 'problem atr', 'nao consegu', 'problem que', 'problem receb'], 
    'Estou tendo o mesmo problema que outra pessoa': ['mesm situaca', 'acontec comig', 'mesm cois'], 
    'Estou irritado/decepcionado': ['est acontec', 'ach que', 'que absurd', 'que decepca', 'que vergonh', 'extrem decepc', 'sup decepc', 'complet decepc', 'to decepc', 'sent roub', 'propagand engan', 'dor cabec', 'tom vergonh', 'total decepc', 'respe consum', 'descas consum', 'falt respe', 'absurd descas', 'verd absurd', 'decepca total', 'mau atend', 'atend mau'],
    'Estou esperando retorno da empresa': ['esper retorn', 'esper que'],
    'Meu problema foi resolvido': ['foi resolv'],
    'Muita demora': ['cheg temp', 'demor receb', 'praz cheg', 'praz receb', 'esper ped', 'mais me', 'ate hoj', 'hoj nao', 'hoj nad', 'demor entreg', 'dia util'],
    'Não compro mais': ['nunc mais', 'prim ult', 'vez que'],
    'Não recomendo a loja': ['nao ped', 'nao recomend', 'recomend ning', 'par ning', 'compr nad', 'compr nao', 'nao compr'],
    'Não resolvem meu problema': ['sempr mesm', 'nao resolv', 'pod resolv', 'numer protocol', 'abr protocol'],
    'Não tenho do que reclamar': ['que reclam'],
    'Ninguém me responde': ['dar retorn', 'tent contat', 'mand mens', 'atend consum', 'canal atend', 'nao funcion', 'nenhum retorn', 'pod retorn', 'sem retorn', 'pod atend', 'tent lig', 'nao atend', 'lix atend', 'pess atend', 'algum retorn', 'cad retorn', 'precis retorn', 'quer retorn', 'fic aguard', 'mand email', 'lig ning', 'respond direct', 'ning at', 'mand direct', 'nao retorn', 'ning retorn', 'nao retornom', 'telefon nao'],
    'Nunca tive problemas com a loja': ['sempr ped', 'tud cert', 'cheg ant', 'sempr cheg', 'sempr compr', 'nao ter', 'ter problem'],
    'Status do pedido está incorreto': ['foi receb', 'const com', 'const receb'],
    'Pedido chegou incorreto': ['ped vir', 'total difer', 'ped err'],
    'Pedido não chegou': ['ate agor', 'previsa entreg', 'nao receb', 'praz entreg', 'cad ped', 'nao cheg', 'nao entreg', 'quer ped', 'precis ped', 'desd temp'],
    'Onde fica a loja física?': ['fic loj'],
    'Tentativa de golpe': ['perfil fals', 'clon whatsapp', 'cuid golp', 'dar golp', 'ped numer'],
    'Preciso da nota fiscal': ['not fiscal'],
    'Preciso de ajuda': ['com faz', 'direct favor', 'ajud favor', 'ajud resolv', 'faz par', 'precis ajud', 'ped favor'],
    'Preciso do código de rastreio': ['codig rastr'],
    'Preciso do código de postagem': ['codig post'],
    'Problema com o pagamento': ['pag bolet', 'carta credit'],
    'Problema com o valor do frete': ['val fret', 'fret gratil', 'pag fret', 'fret mais', 'fret car', 'fret absurd', 'dinh fret', 'fret ta'],
    'Problema com a troca': ['nao val', 'val troc', 'solic troc', 'troc ped', 'faz troc'],
    'Problema na entrega': ['foi cheg', 'separaca estoc', 'que transport', 'diz que'],
    'Problema com a devolução': ['devoluca ped'],
    'Desconfio da promoção': ['prec que', 'propagand eng'],
    'Recebi o pedido': ['receb hoj', 'ant praz'],
    'Quero cancelar o pedido': ['cancel ped'],
    'Quero cupom de desconto': ['cupom descont'],
    'Quero o dinheiro de volta': ['devolv dinh', 'dinh volt', 'quer dinh', 'cad dinh', 'sem dinh'],
    'Quero saber sobre meu pedido': ['gost sab', 'quer sab', 'sobr ped', 'ped est'],
    'Spam': ['http www', 'http s'],
    'Tenho receio de comprar': ['ia compr', 'tant reclamaca', 'comentari nega', 'obrig dic', 'algu compr', 'quant reclamaca', 'ler comentari'],
    'Vou tomar providência': ['procur direit', 'direit consum', 'ter que', 'reclam aqu', 'acion procon', 'consum gov', 'gov br', 'procon sp', 'abr reclamaca', 'reclamaca procon'],
}


# "Sentimento": agrupamento de clusters
positivos = ['Nunca tive problemas com a loja', 
           'Recebi o pedido',
           'Amei comprar', 
           'Meu problema foi resolvido', 
           'Não tenho do que reclamar'
]

negativos = [
    'Estou irritado/decepcionado', 
    'Muita demora', 
    'Quero o dinheiro de volta', 
    'Não compro mais', 
    'Estou tendo uma experiência ruim', 
    'Tenho receio de comprar', 
    'Não compro mais', 
    'Vou tomar providência', 
    'Não recomendo a loja',
    'Estou tendo um problema',
    'Estou tendo o mesmo problema que outra pessoa',
    'Não resolvem meu problema',
    'Ninguém me responde',
    'Estou esperando retorno da empresa',
    'Desconfio da promoção',
    'Endereço incorreto',
    'Pedido não chegou',
    'Problema na entrega',
    'Pedido chegou incorreto',
    'Preciso da nota fiscal',
    'Preciso de ajuda',
    'Preciso do código de rastreio',
    'Preciso do código de postagem',
    'Problema com a troca',
    'Problema com o valor do frete',
    'Problema com o pagamento',
    'Problema com a devolução',
    'Quero cancelar o pedido',
    'Quero saber sobre meu pedido',
    'Status do pedido está incorreto',
    'Tentativa de golpe'
]

outros = ['Quero cupom de desconto', 'Onde fica a loja física?', 'Spam']

sentimentos = {'Positivo': positivos, 'Negativo': negativos, 'Outro': outros} # resumo


# "Problema": quando o problema do cluster é identificável
problemas = {'Entrega não efetuada': ['Quero saber sobre meu pedido', 'Pedido não chegou', 'Problema na entrega', 'Status do pedido está incorreto'],
    'Entrega efetuada, porém incorreta': ['Pedido chegou incorreto'],
    'Cancelamento': ['Quero cancelar o pedido'],
    'Devolução': ['Problema com a devolução'],
    'Pagamento': ['Problema com o pagamento'],
    'Preço do frete': ['Problema com o valor do frete'],
    'Código de rastreio': ['Preciso do código de rastreio'],
    'Código de postagem': ['Preciso do código de postagem'],
    'Nota fiscal': ['Preciso da nota fiscal'],
    'Tentativa de golpe': ['Tentativa de golpe'],
    'Endereço': ['Endereço incorreto'],
    'Outros problemas': ['Preciso de ajuda'],
    'Troca': ['Problema com a troca']
}


# palavras obrigatórias para classificação (lematizadas e sem acento)
mandatory = ['pedido',
    'loja',
    'chegar',
    'comprar',
    'tempo',
    'nunca',
    'hoje',
    'numero',
    'pedir',
    'preco',
    'conseguir',
    'mandar',
    'recebido',
    'agora',
    'entrar',
    'retorno',
    'propaganda',
    'loja',
    'lojar',
    'entregar',
    'dinheiro',
    'email',
    'receber',
    'problema',
    'consumidors',
    'retornom',
    'empresa',
    'recolher',
    'comentario',
    'acontecer',
    'descasar',
    'suportar',
    'separacao',
    'promocao',
    'retornor',
    'desconto',
    'processar',
    'enviar',
    'resolver',
    'responder',
    'trocar',
    'contato',
    'postagem',
    'cliente',
    'entregue',
    'esperar',
    'atendimento',
    'resposta',
    'aguardar',
    'reclamacao',
    'reputacao',
    'devolver',
    'prazo',
    'retornar',
    'ligar',
    'mau',
    'telefonar',
    'transportador',
    'codigo',
    'vale',
    'dm',
    'favor',
    'cancelar',
    'consumidor',
    'direct',
    'rastrear',
    'devolucao',
    'respeitar',
    'procon',
    'mensagem',
    'solicitar',
    'informar',
    'absurdo',
    'constar',
    'golpe',
    'enderecar',
    'esclarec',
    'atrasar',
    'descaso',
    'ajudar',
    'protocolo',
    'estocar',
    'cartao',
    'ninguem',
    'pagamento',
    'informacao',
    'demorar',
    'atender',
    'reclamar',
    'acabar',
    'cade',
    'decepcionar',
    'reclame',
    'fretar',
    'falir',
    'coletar',
    'correio',
    'clonar',
    'whatsapp',
    'perfil',
    'direito',
    'solucao',
    'situacao',
    'erro',
    'sac',
    'rapido',
    'aplicativo',
    'cupom',
    'ultima',
    'previsao',
    'roubar',
    'chamar',
    'cancelamento',
    # 'amar',
    'recomendar',
    'fiscal',
    'boletar',
    'vergonha',
    # 'amor',
    'medo',
    'ligacao',
    'decepcao',
    'rastreamento',
    'posicao',
    # 'satisfacao',
    'desistir',
    'automatico',
    'processo',
    # 'adorar',
    'parabens',
    'qualidade',
    'pos-venda',
    'lixo',
    'experiencia',
    'demorar',
    'compromisso'
 ]